routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/ 
Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['register' => true]);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')
        ->name('home');
    Route::resource('users', 'UserController');
    Route::resource('wallets', 'WalletController');
    Route::resource('vehicles', 'VehicleController');
    Route::resource('mileages', 'MileageController');
    Route::resource('rewards', 'RewardController');
    Route::resource('redeem-gifts', 'RedeemGiftController');
    Route::resource('ratings', 'RatingController');


    Route::resource('companies', 'CompanyController');
    Route::resource('petrol-pumps', 'PetrolPumpController');
    Route::resource('packages', 'PackageController');

    Route::get('change-password', 'UserController@changePassword')->name('change-password');
    Route::post('change-password', 'UserController@updateChangePassword')->name('update-password');
    Route::resource('permissions', 'PermissionController');
   
    Route::resource('roles', 'RoleController');
    Route::resource('prices', 'PriceController');

    Route::resource('transactions', 'TransactionController');
    Route::resource('promotions', 'PromotionController');
    Route::get('ajax/request', 'CompanyController@ajaxRequest')->name('ajax.request');

    Route::resource('logger', 'LoggerController'); 
    Route::resource('services', 'ServiceController'); 
    Route::DELETE('service-detail/{serviceDetail}', 'ServiceController@delete')->name('services.delete');

    Route::post('add-service-detail', 'ServiceController@addServiceDetail')->name('services.add');
     

Route::get('logger-graph', 'LoggerController@graph')->name('logger.graph');

     
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\App;
use Laravel\Sanctum\HasApiTokens;

use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

use Spatie\Permission\Traits\HasRoles;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;
use Yadahan\AuthenticationLog\AuthenticationLogable;
use Spatie\Activitylog\Traits\LogsActivity;

class User extends Authenticatable implements HasMedia
{
    use HasApiTokens, HasFactory, Notifiable, InteractsWithMedia, HasRoles, SoftDeletes, AuthenticationLogable;
    use LogsActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'company_id',
        'emp_code',
        'name',
        'email',
        'mobile',
        'password',
        'about_me',
        'address',
        'status'
    ];


    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
     
    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')
            ->width(128)
            ->height(128);
    }
    
    public function registerMediaCollections(): void
    {
        // echo config('app.avatar');
        // exit;
        $this
            ->addMediaCollection('avatar')
            ->useFallbackUrl(config('app.asset_url') . config('app.avatar'))
            ->singleFile();
    }

    // Cache permissions and roles
    public function getPermissionsAttribute()
    {
        $permissions = Cache::rememberForever('permissions_cache', function () {
            return Permission::select('permissions.*', 'model_has_permissions.*')
                ->join('model_has_permissions', 'permissions.id', '=', 'model_has_permissions.permission_id')
                ->get();
        });

        return $permissions->where('model_id', $this->id);
    }
 
    static function loginLog($request, $user_id)
    {
        $user_log = [];
        $user_log['authenticatable_type'] = "App\Models\User";
        $user_log['authenticatable_id'] = $user_id;
        $user_log['ip_address'] = $request->ip();
        $user_log['user_agent'] =  $request->userAgent();
        $user_log['login_from'] = "api";
        $user_log['extra_info'] = json_encode($request->extra_info);
        $user_log['login_at'] = Carbon::now();
        DB::table('authentication_log')->insert($user_log);
    }

     
    /**
     * Get All supervisor
     */
    static function getAllAppUser()
    {
        return self::where(['status' => 1])
            ->whereHas('roles', function ($query) {
                $query->where('role_id', 2);
            })
            ->orderBy('name')
            ->pluck('name', 'id');
    }

    /**
     * Scope a query to only include login user vendor id.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    
 
    static function userTokenDelete($user)
    {
        if ($user->status == 0) {
            $user->tokens()->delete();
        }
    }

    
    /* Define many to many relation */
     

    public function packages()
    {
         return $this->belongsToMany(Package::class)->withPivot(['package_id','user_id','transaction_id','from_date','to_date','cost','discount','discount_percentage', 'reward_point','cashback','status'])->withTimestamps();
    }  

     
    /**
     * @return HasOne
     * @description get the detail associated with the post
     */
    public function profile() 
    {
        return $this->hasOne(Profile::class);
    }

    public function redeem()
    {
         return $this->belongsToMany(RedeemGift::class)->withPivot(['redeem_gift_id','user_id','redeem_code','redeem_point','use_date','status'])->withTimestamps();
    }

    public function address()
    {
        return $this->hasMany(Address::class);
    }
    
    public function service()
    {
        
         return $this->belongsToMany(Service::class)->withPivot(['id','service_id','user_id','pickup_address','service_date','slot_id','service_start_time','service_end_time','service_status','payment_no','payment_no','order_no','payment_date','payment_status'])->withTimestamps();
    } 
}

app/Http/Controllers/Api/V1/UserController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Validator;
use App\Models\{User,Profile,Rating,Address,Otp};
use Illuminate\Support\Str;
use Auth,Hash, DB;
use Illuminate\Support\Facades\Mail;
use App\Mail\SignupMail;
 
class UserController extends Controller
{
    /**
     * User Profile 
     */
    function updateProfile(Request $request)
    {
        $status = false;
        $message = __('api.try_again');    
        $user_id = $request->user()->id;
        $validator = Validator::make($request->all(), [
            'mobile' => 'required|digits:10|unique:App\Models\User,mobile,'. $user_id,
            'name' => 'required',
            'email' => 'required|email|unique:App\Models\User,email,'. $user_id,
            'package_id' => 'required|numeric',
            'term_accepted'=>'required|numeric|gt:0'
        ]);
        
        if ($validator->fails()) {
            $response['errors'] = $validator->errors();
            return $this->sendResponse($response);
        }
       
        $user = User::find($user_id);
        $user['mobile'] = $request->mobile;
        $user['email'] = $request->email;
        $user['name'] = $request->name;
      
        if ( $user->update()) {
            $insertProfile['user_id']=$user_id;
            $insertProfile['package_id']=$request->package_id;
            $insertProfile['term_accepted']=$request->term_accepted;
            $user->profile()->updateOrCreate(['user_id'=>$user_id],$insertProfile);
            $response['status'] = true;
            $message = __('api.update',['title'=>'user profile']);
        } else {
            $status = false;
            $message = __('api.try_again');    
        }
        $response['message'] = $message;
        return $this->sendResponse($response);
    }
    /**
     * User login using mobile
     */
    function login(Request $request)
    {
        $response = [];
        $message = null;
        $validator = Validator::make($request->all(), [
            'mobile' => 'required|digits:10|numeric',
        ]);
        if ($validator->fails()) {
            $response['errors'] = $validator->errors();
            return $this->sendResponse($response);
        }
        
        $user = User::with(['roles'])
       ->where('mobile', $request->post('mobile'))->first();
        $otp = Otp::generateNumericOTP();
        if ($user) 
        {
            if($user->status==1 && $user->roles[0]->id==2)
            {
                $user_id = $user->id;
                Otp::generateOtp($user_id, $request->mobile, $otp);
                if ($otp) {
                // sendSMS($request->mobile, $otp, '');
                }
                $response['status'] = true;    
                $message = __('api.login_success');
            }
            else
            {
            $response['status'] = false;    
            $message = __('api.login_fail');    
            }
        } 
        else 
        {
            Otp::generateOtp(0, $request->mobile, $otp);
            if ($otp) {
               // sendSMS($request->mobile, $otp, '');
            }
            $response['status'] = true;
            $message = __('api.login_success');
        }
        $response['message'] = $message;
        return $this->sendResponse($response);
    }


    /**
     * Verify OTP
     */
    function verify(Request $request)
    {
        $response = [];
        $message = null;
        $validator = Validator::make($request->all(), [
            'mobile' => 'required|digits:10',
            'otp' => 'required|digits:4',
        ]);
        if ($validator->fails()) {
            $response['errors'] = $validator->errors();
            return $this->sendResponse($response);
        }
        $otp = $request->post('otp');
        $user = User::select('users.id', 'name', 'users.mobile')->where('users.mobile', $request->post('mobile'))
            ->whereHas('roles', function ($query) {
                $query->where('role_id', 2);
            })
            ->with('profile')
            ->where('users.status', 1)
            ->first();
           
            if ($user) {
            if (Otp::verify($request->mobile, $otp) || $otp == 1234) {
           // if ($otp == 1234) {
                # store user history for tracking
                User::loginLog($request, $user->id);
                # creating user token
                $user->tokens()->delete();
                $token = $user->createToken('mytoken')->plainTextToken;
                if($user->profile->package_id==0)
                    {
                        $profile_status = false;
                    }
                    else
                    {
                        $profile_status = true;
                    }
                $response['data'] = ['user' => $user->only(['id','name', 'mobile']), 'token' => $token,'profile_status'=>$profile_status];
                $message = __('api.verify_success');
            } else {
                $response['status'] = false;
                $message = __('api.verify_fail');
            }
        } else {
            if (Otp::verify($request->mobile, $otp) || $otp == 1234)  
            //if ($otp == 1234) 
             {
                # create new user
                $input['mobile'] = $request->post('mobile');
                $input['status'] = 1;
                $input['company_id'] = 0;
                $newuser = User::create($input);
                # create profile
                $newuser->profile()->updateOrCreate(['user_id'=>$newuser->id],['user_id'=>$newuser->id]);

                if($newuser)
                {
                    # Assign user role
                    $newuser->assignRole(2);
                }
                # store user history for tracking
                User::loginLog($request, $newuser->id);
                # creating user token
                $token = $newuser->createToken('mytoken')->plainTextToken;
                $response['data'] =  ['user' => $newuser->only(['id','name', 'mobile']),'token' => $token,'profile_status'=>false];
                $message = __('api.verify_success');
             } 
            else {
                $response['status'] = false;
                $message = __('api.verify_fail');
            }
        }
        $response['message'] = $message;
        return $this->sendResponse($response);
    }

    /**
     * Get User status
     */
    function user(Request $request)
    {
       $data =[];

       $userStatus = $request->user();
       $data =  $userStatus->only(['status']);
       $user_id = $request->user()->id;
       $user =  User::find($user_id) 
        ->profile
        ->select('profiles.package_id','package_user_id','package_user.to_date')
        ->leftJoin('package_user',[['package_user.id','=','package_user_id'],['package_user.user_id','=','profiles.user_id']])
        ->where(['profiles.user_id'=>$user_id])
        ->first();
        
        if($user->package_id==0)
        {
            $data['profile_status'] = false;
            $data['package_status'] = 'User not purchase any package yet';
        }
        elseif($user->package_id>0 && strtotime($user->to_date) < strtotime(date('Y-m-d')))
        {
            $data['profile_status'] = false;
            $data['package_status'] = "Package Expired form ".$user->to_date;
        }
        else
        {
            $data['profile_status'] = true;
            $data['package_status'] = "Package Active";
        }
        $response['data'] = ['user' => $data];
        
       // $user = $request->user();
        //$response['data'] = ['user' => $user->only(['status'])];
        return $this->sendResponse($response);
    }


    /**
     * After successfully login
     */
    function home()
    {
        $response['data'] = ['home' => 'Welcome Dashboard'];
        return $this->sendResponse($response);
    }

    /**
     * User logout 
     */
    function logout(Request $request)
    {
        $request->user()->currentAccessToken()->delete();
        $response['message'] = __('api.logout');
        $response['data'] = [];

        return $this->sendResponse($response);
    }

    /**
     * User profile
     */
    function profile(Request $request)
    {
        $status = false;
        $message = __('api.try_again');
        
        $user = User::select('users.id', 'users.name','users.email', 'users.mobile',  'packages.package_name', 'profiles.wallet_amount','profiles.reward_point','profiles.cashback','package_user.from_date', 'package_user.to_date', 'package_user.cost', DB::raw("CASE WHEN fu_package_user.to_date >= Current_date() THEN 'Active' Else 'Expired' END as planStatus, IFNULL(DATEDIFF(fu_package_user.to_date,current_date()),0) as remainingDays "))
        ->leftjoin('profiles','profiles.user_id', '=', 'users.id')
        ->leftJoin('package_user', [['package_user.id', '=', 'profiles.package_user_id'],['package_user.package_id', '=', 'profiles.package_id'],['package_user.user_id', '=', 'profiles.user_id']])
        ->leftJoin('packages', 'packages.id', '=', 'profiles.package_id')
        ->where('users.id', $request->user()->id)->get();
        $response['data']['user'] = $user;
        if ($user) {
            $status = true;
            $message = __('api.detail', ['title' => 'User']);
        }
        $response['status'] = $status;
        $response['message'] = $message;
        
        return $this->sendResponse($response);
    }

    /** Add/Update Petrol Pump Rating from User  */

    function rating(Request $request)
    {
        $status = false;
        $message = __('api.try_again');    
        $validator = Validator::make($request->all(), [
            'petrol_pump_id' => 'required|numeric',
            'transaction_id' => 'required|numeric',
            'rating' => 'required'
        ]);
        if ($validator->fails()) {
            $response['errors'] = $validator->errors();

resources/views/users/change-password.blade.php
<!-- Layout  -->
@extends('layouts.admin')
@php
$title = 'Change Password';
$href = route('users.index');
@endphp
@section('title')
    {{ $title }}
@endsection
@section('content')
    <x-card :title="$title">
        <x-form method="post" action="{{ route('update-password') }}">
            <x-input name="password" id="password" title="Password" type="password" label_class="required" />
            <x-input name="password_confirmation" title="Confirm Password" type="password" label_class="required" />
        </x-form>
    </x-card>
@endsection

@push('after-scripts')
    <script>
        $(document).ready(function() {
            $(".form").validate({
                rules: {
                    password: {
                        required: true,
                        minlength: 8,
                        maxlength: 30
                    },
                    password_confirmation: {
                        equalTo: "#password"
                    }
                }

            });
        });
    </script>
@endpush

resources/views/users/create.blade.php
<!-- Layout  -->
@extends('layouts.admin')
@php
$title = __('messages.create', ['title' => 'User']);
$href = route('users.index');
@endphp
@section('title')
    {{ $title }}
@endsection
@section('content')
    <x-card :title="$title">
        <x-slot name="header_right">
            <x-link href="{{ $href }}" />
        </x-slot>
        <x-form method="post" enctype="multipart/form-data" action="{{ route('users.store') }}">
            <x-input name="name" title="Name" label_class="required" />
            <x-input name="mobile" title="Mobile" type="number" />
            <x-input name="email" title="Email" type="email" label_class="required" />
            <x-input name="password" title="Password" type="password" label_class="required" />
            <x-input name="password_confirmation" title="Confirm Password" type="password" label_class="required" />
            <x-input name="avatar" title="Profile Image" type="file" />
            <x-input name="about_me" title="About Me" type="textarea" />
            <x-select name="role" title="Role" label_class="required" :options="$roles" />
            <x-status />
            <div class="mb-3 row">
                <label class="col-sm-4 col-form-label"></label>
                <div class="col-sm-8">
                    <div class="form-check">
                        <input class="form-check-input" id="login_detail" name="login_detail" value="1" type="checkbox">
                        <label class="form-check-label" for="login_detail">Login detail send</label>
                    </div>
                </div>
            </div>
        </x-form>
    </x-card>
@endsection

@push('after-scripts')
    <script>
        $(document).ready(function() {
            $(".form").validate({
                rules: {

                }

            });
        });
    </script>
@endpush

resources/views/users/edit.blade.php
<!-- Layout  -->
@extends('layouts.admin')
@php
$title = __('messages.edit', ['title' => 'User']);
$href = route('users.index');
$avatar = $user->getFirstMediaUrl('avatar', 'thumb');
@endphp
@section('title')
    {{ $title }}
@endsection
@section('content')
    <x-card :title="$title">
        <x-slot name="header_right">
            <x-link href="{{ $href }}" />
        </x-slot>

        {!! Form::model($user, ['method' => 'PUT', 'enctype' => 'multipart/form-data', 'class' => 'form', 'route' => ['users.update', $user->id]]) !!}
        <x-input name="name" title="Name" label_class="required" />
        <x-input name="mobile" title="Mobile" type="number" />
        <x-input name="email" title="Email" type="email" label_class="required" />
        <x-input name="avatar" title="Profile Image" type="file" :selected="$avatar" />
        <x-input name="about_me" title="About Me" type="textarea" />
        <!--x-select name="role" title="Role" label_class="required" :options="$roles" :selected="$user_has_role" /-->
        <x-status />
        <div class="mb-3 row">
            <div class="col-sm-8 offset-sm-4">
                <x-button />
            </div>
        </div>
        {!! Form::close() !!}
    </x-card>
@endsection

@push('after-scripts')
    <script>
        $(document).ready(function() {
            $(".form").validate({
                rules: {

                }

            });
        });
    </script>
@endpush

resources/views/users/index.blade.php
<!-- Layout  -->
@extends('layouts.admin')
@php
$title = __('messages.list', ['title' => 'User']);
$href = route('users.create');
$tableHeader = ['#', 'Avatar', 'Name', 'Mobile', 'Email', 'Role', 'Status', 'Created At', 'Last Login', 'Action'];
@endphp
@section('title')
    {{ $title }}
@endsection
@section('content')
    <x-card :title="$title">
        @can('user-create')
            <x-slot name="header_right">
                <x-link href="{{ $href }}" title="{{ __('messages.create', ['title' => 'user']) }}"
                    icon="fa-plus-circle" />
            </x-slot>
        @endcan
        <x-form with_button="search" method="get" action="{{ route('users.index') }}">
            <div class="row">
                <x-select name="role" title="Role" :options="$roles" class="col-md-3 col-lg-3 col-xl-2" form_type="v" />
                <x-input name="s" title="Search" placeholder="name,email" class="col-md-3 col-lg-3 col-xl-2" form_type="v" />
                <x-input name="mobile" title="Mobile" placeholder="Mobile No." class="col-md-3 col-lg-3 col-xl-2" form_type="v" />
                <x-status search />
                <x-button type="primary form-control" text="Search" icon="fa-search" button_type="search" />
            </div>

        </x-form>
        <x-table :table_header="$tableHeader" :data="$users" pagination="true">
            @forelse ($users  as $user)
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>
                        @php
                            $avatar = $user->getFirstMediaUrl('avatar', 'thumb');
                        @endphp
                        @if ($avatar)
                            <div class="avatar"><img class="avatar-img avatar-img-small"
                                    src="{{ $avatar }}"><span class=""></span>
                            </div>
                        @endif
                    </td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->mobile }}</td>
                    <td>{{ $user->email }}</td>
                    <td>

                        @if (!empty($user->getRoleNames()))
                            @foreach ($user->getRoleNames() as $v)
                                <label class="mr-4">{{ $v }}</label>
                            @endforeach
                        @endif
                    </td>
                    <td>

                        <x-status text="{{ $user->status }}" />

                    </td>
                    <td>
                        <x-dt :date_time="$user->created_at" format="j M y" />


                    </td>
                    <td>
                        <x-dt :date_time="$user->lastLoginAt()" />

                    </td>
                    <td>
                        @can('user-edit')
                        <x-link title="View" icon="fa-eye" href="{{ route('users.show', $user->id) }}" />
                            <x-link title="Edit" icon="fa-edit" href="{{ route('users.edit', $user->id) }}" />
                        @endcan
                        @can('user-delete')
                            <x-delete action="{{ route('users.destroy', $user->id) }}" />
                        @endcan
                    </td>
                </tr>
            @empty
                <x-norecord colspan="10" />
            @endforelse

        </x-table>
    </x-card>
@endsection

resources/views/users/mileage.blade.php
<!-- Layout  -->
@php
$tableHeader = ['#',  'Meter Reading', 'Created At' ];
$mileage_title = 'User Mileage List';
@endphp
    <x-card :title="$mileage_title">
       
    <x-table :table_header="$tableHeader" :data="$mileages" pagination="true">
            @forelse ($mileages  as $mileage )
                <tr>
                    <td>{{ ++$i }}</td>
                     
                    <td>{{ $mileage->meter_reading }}</td>
                      
                    <td>
                        <x-dt :date_time="$mileage->created_at" />
                    </td>
                     
                </tr>
            @empty
                <x-norecord colspan="3" />
            @endforelse

        </x-table>
    </x-card> 

resources/views/users/package.blade.php
<!-- Layout  -->
@php
$tableHeader = ['#','Package', 'Payment No', 'Cashback', 'Reward', 'Cost', 'From date', 'To date', 'Created At'];
$package_title = 'User Purchase Package List';
@endphp
    <x-card :title="$package_title">
       
    <x-table :table_header="$tableHeader" :data="$userPackage" pagination="true">
        @forelse ($userPackage   as $package )
            <?php   
           if($package->packages->count() > 0){
            $myPackage = array();
            $myPackage = $package->packages;
           
                for($j=0; $j < count($myPackage);$j++)
                {  ?>
                <tr>
                    <td>{{ $j+1 }}</td>
                    <td>{{ $myPackage[$j]->package_name }}</td>
                    <td>{{ $myPackage[$j]->payment_no }}</td>
                    <td>{{ $myPackage[$j]->cashback }}</td>
                    <td>{{ $myPackage[$j]->reward_point }}</td>
                    <td>{{ $myPackage[$j]->cost }}</td>
                    <td>{{ $myPackage[$j]->from_date }}</td>
                    <td>{{ $myPackage[$j]->to_date }}</td>
                    <td>
                        <x-dt :date_time="$myPackage[$j]->created_at" />
                    </td>
                </tr>
              <?php  } } else { ?>
                <x-norecord colspan="9" />
               <?php  }?> 
            @empty
                <x-norecord colspan="9" />
            @endforelse

        </x-table>
    </x-card> 

resources/views/users/profile.blade.php
@extends('backend.base')

@section('content')

    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    @include('backend.shared.alert')


                    <div class="card">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            Profile
                        </div>
                        @php
                            $avatar = $user->getFirstMediaUrl('avatar', 'thumb');
                        @endphp

                        {!! Form::model($user, ['method' => 'patch', 'enctype' => 'multipart/form-data', 'route' => ['profile.update']]) !!}
                        <div class="card-body">
                            @include('backend.shared.ui.text',['label'=>'Name','name'=>'name','required'=>true])
                            @include('backend.shared.ui.email',['label'=>'Email','name'=>'email','required'=>true])
                            @include('backend.shared.ui.file',['label'=>'Profile
                            Image','name'=>'avatar','url'=>$avatar])
                            @include('backend.shared.ui.textarea',['label'=>'About Me','name'=>'about_me'])
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-sm btn-primary" type="submit"> Save</button>
                        </div>
                        {!! Form::close() !!}

                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/users/transaction.blade.php
<!-- Layout  -->
@php
$tableHeader = ['#',  'Package','Petrol Pump', 'Amount','Reward','Cashback','Status', 'Payment Id', 'Created At'];
$status = array("pending"=>"Pending","success"=>"Success","failed"=>"Failed");
$transaction_title = 'User Transaction History (Cashback & Rewards)';
@endphp
    <x-card :title="$transaction_title">
    <x-form with_button="search" method="get" action="{{ route('users.show', $user->id) }}">
            <div class="row">
            <x-select name="package_id" title="Package" :options="$package" form_type="v"  class="col-md-2" />
            <x-select name="petrol_pump_id" title="Petrol Pump" :options="$petrolPumps" form_type="v"  class="col-md-2" />
                <div class="col-md-2 form-group col-md-3 col-lg-3 col-xl-2">
                    <label for="form_date" class="">From Date</label>
                    <input type="text" class="form-control from_date" placeholder="From Date" name="from_date" value="<?= app('request')->input('from_date')?>"  />
                
                </div>

                <div class="col-md-2 form-group col-md-3 col-lg-3 col-xl-2">
                    <label for="to_date" class="">To Date </label>
                    <input type="text" class="form-control to_date" placeholder="To Date" name="to_date" value="<?= app('request')->input('to_date')?>"  />
                
                </div>
                <x-select name="status" title="Status" :options="$status" form_type="v"  class="col-md-2" />
                <x-button type="primary form-control" text="Search" icon="fa-search" button_type="search" />
            </div>

        </x-form>
        <x-table :table_header="$tableHeader" :data="$rewards" pagination="true">
            @forelse ($rewards  as $reward )
                <tr>
                    <td>{{ ++$i }}</td>
                    
                    <td>{{ $reward->package->package_name }}</td>
                    <td>
                        {{ $reward->petrolPump->name }}
                     ({{ $reward->petrolPump->company->company_name }})
                    </td> 
                    
                    <td>{{ $reward->amount }}</td>
                    <td>{{ $reward->reward_point }}</td>
                    <td>{{ $reward->cashback }}</td>
                    <td>{{ Ucfirst($reward->status) }}</td> 
                    <td>{{ $reward->payment_no }}</td>
                      
                    <td>
                        <x-dt :date_time="$reward->created_at" />

                    </td>
                     
                </tr>
            @empty
                <x-norecord colspan="11" />
            @endforelse

        </x-table>
    </x-card> 