routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/ 
Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['register' => true]);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')
        ->name('home');
    Route::resource('users', 'UserController');
    Route::resource('wallets', 'WalletController');
    Route::resource('vehicles', 'VehicleController');
    Route::resource('mileages', 'MileageController');
    Route::resource('rewards', 'RewardController');
    Route::resource('redeem-gifts', 'RedeemGiftController');
    Route::resource('ratings', 'RatingController');


    Route::resource('companies', 'CompanyController');
    Route::resource('petrol-pumps', 'PetrolPumpController');
    Route::resource('packages', 'PackageController');

    Route::get('change-password', 'UserController@changePassword')->name('change-password');
    Route::post('change-password', 'UserController@updateChangePassword')->name('update-password');
    Route::resource('permissions', 'PermissionController');
   
    Route::resource('roles', 'RoleController');
    Route::resource('prices', 'PriceController');

    Route::resource('transactions', 'TransactionController');
    Route::resource('promotions', 'PromotionController');
    Route::get('ajax/request', 'CompanyController@ajaxRequest')->name('ajax.request');

    Route::resource('logger', 'LoggerController'); 
    Route::resource('services', 'ServiceController'); 
    Route::DELETE('service-detail/{serviceDetail}', 'ServiceController@delete')->name('services.delete');

    Route::post('add-service-detail', 'ServiceController@addServiceDetail')->name('services.add');
     

Route::get('logger-graph', 'LoggerController@graph')->name('logger.graph');

     
});

app/Models/PetrolPump.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;
use DB;
class PetrolPump extends Model
{
    use HasFactory,SoftDeletes, LogsActivity;

    protected $fillable = [
        'company_id',
        'price_id',
        'code', 
        'beacon_id',
        'name',
        'address',
        'pincode',
        'latitude',
        'longitude',
        'opening_time',
        'closing_time',
        'status'
    ];

    protected $casts = [
        'created_at' => 'datetime:d-m-Y h:i a',
        
    ];
    // One to One Relation with office
    public function price()
    {
        return $this->belongsTo(Price::class);
    }

    
    /* Relation one-one with company */
    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * Get All
     */

    static function getAll($request = null)
    {
           
            if (createAction()) {
                return self::active()->orderBy('name')->pluck('name', 'id');
            }
            return self::where($request)->orderBy('name')->pluck('name', 'id');
       
    }



    static function scopeActive($query)
    {
        return $query->where('status', 1);
    }

    function scopeCondition($query, $request)
    {
        $query->where(function ($query)  use ($request) {
            $company_id = $request->get('company_id');
            $s = $request->s;
            if ($company_id) {
                $query->where('company_id', $company_id);
            }
            if(loginUserCompanyId() && loginUserRoleId()==3)
            {
                $query->where('company_id',loginUserCompanyId());
            }
            if($request->price_id){
                $query->where('price_id', $request->price_id);
            }
            if ($s) {
                $query->where('name', 'LIKE', "%$s%");
            }
            if($request->code){
                $query->where('code','LIKE',"%$request->code%");
            }
            if ($request->has('status')) {
                $status = $request->status;
                if ($status) {
                    $query->where('status', $status);
                } else if ($status === '0') {
                    $query->where('status', $status);
                }
            }
        });
    }

    public function petrolPumpUserRating()
    {
        return $this->belongsToMany(PetrolPump::class,'ratings')->withPivot(['petrol_pump_id','user_id','rating'])->withTimestamps();
    }  

    static function getPetrolPump()
    {
        $whereArr = [];
        if(createAction()==false) 
        {
         $whereArr['status'] = 1; 
        }
         if(loginUserCompanyId())
        $whereArr['company_id'] = loginUserCompanyId();

        $petrolPump = self::select(DB::raw("CONCAT(name,' (',code,')') AS name"),'id')
       ->where($whereArr)
       ->orderBy('name')->pluck('name', 'id');
       return   $petrolPump;
    }
}

app/Http/Controllers/Api/V1/PetrolPumpController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\{Company,PetrolPump,Price};
use Validator;
use Illuminate\Validation\Rule;
Use DB;

class PetrolPumpController extends Controller
{
    /**
     * Display a Petrol Pump listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $status = false;
        $message = __('api.no_record');
        $petrolPump = PetrolPump::select('petrol_pumps.id', 'company_id','beacon_id','price_id', 'code', 'name', 'address','pincode','latitude','longitude', 'opening_time', 'closing_time', 'status', 'petrol_pumps.created_at', DB::raw('ROUND(IFNULL(avg(rating),0),2) as rating'))
        ->with(['company' => function ($query) {
            $query->select('id', 'company_name')->with(['media']);
             }])
        ->with(['price' => function ($query) {
        $query->select('id','state_code','state_name','petrol_cost');
            }])
            ->leftJoin('ratings', [['ratings.petrol_pump_id','=','petrol_pumps.id']])
            ->where('status', 1)
            ->groupBy('petrol_pumps.id')
            ->orderBy('id','desc')
            ->get();
        if ($petrolPump->count()) {
              foreach ($petrolPump as $pump) {
                    $pump->company_logo = ($pump->company->getFirstMediaUrl('company_logo'))?$pump->company->getFirstMediaUrl('company_logo'):asset('img/default.png');

                    $pump->company_logo_thumb = ($pump->company->getFirstMediaUrl('company_logo','thumb'))?$pump->company->getFirstMediaUrl('company_logo','thumb'):asset('img/default.png');
                   }
            $status = true;                    
            $response['data']['petrolPump'] = $petrolPump;
            $message = __('api.list', ['title' => 'Petrol Pump']);
        }
        $response['message'] = $message;
        $response['status'] = $status;
        return $this->sendResponse($response);
    }
    /**
     * Display a Fuel price listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function price(Request $request)
    {
        $status = false;
        $message = __('api.no_record');

        $price = Price::select('id', 'state_name', 'state_code', 'petrol_cost', 'diesel_cost','cng_cost', 'updated_at')
         ->orderBy('state_name','ASC')
        ->get();
        if ($price->count()) {
            $status = true;
            $response['data']['price'] = $price;
            $message = __('api.list', ['title' => 'Price']);
        }
        $response['message'] = $message;
        $response['status'] = $status;
        return $this->sendResponse($response);
    }

}

app/Http/Controllers/PetrolPumpController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\{Company,PetrolPump,Price,Rating}; 
use App\Http\Requests\{StorePetrolPumpRequest, UpdatePetrolPumpRequest};
use DB; 
class PetrolPumpController extends Controller
{
    private $title;
    private $companies;
    private $prices;

    public function __construct()
    {
        $this->title = "Petrol Pump";
        $this->companies = Company::getAll();
        $this->prices = Price::getAll();
        $this->middleware('permission:petrol-pump-list', ['only' => ['index']]);
        $this->middleware('permission:petrol-pump-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:petrol-pump-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:petrol-pump-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      
        $petrolPumps = PetrolPump::select('petrol_pumps.id','price_id', 'company_id', 'code', 'name', 'beacon_id','address','pincode','latitude','longitude', 'status', 'opening_time', 'closing_time', 'petrol_pumps.created_at'
        , DB::raw('ROUND(IFNULL(avg(rating),0),2) as rating'))
            ->with(['company' => function ($query) {
                $query->select('id', 'company_name');
            }])
            ->with(['price' => function ($query) {
                $query->select('id', 'state_name','petrol_cost');
            }])
            ->leftJoin('ratings', [['ratings.petrol_pump_id','=','petrol_pumps.id']])
            ->condition($request)
            ->groupBy('petrol_pumps.id')
            ->orderBy('id', 'desc')
            ->paginate();

            
        return view('petrol-pumps.index', compact('petrolPumps'))->with(['title' => $this->title,'companies'=> $this->companies,'prices'=>$this->prices]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('petrol-pumps.create')->with(['companies' => $this->companies, 'title' => $this->title,'prices'=>$this->prices]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\StorePetrolPumpRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePetrolPumpRequest $request)
    {
        $petrolPump = PetrolPump::create($request->all());
        if ($petrolPump) {
            return redirect()->route('petrol-pumps.index')
                ->with('success', __('messages.insert', ['title' => $this->title]));
        } else {
            return redirect()->back()->with('error', __('messages.try_again'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(PetrolPump $petrolPump)
    {
        $loginUserCompanyId = loginUserCompanyId();
        $loginUserRoleId = loginUserRoleId();
        if($loginUserCompanyId > 0)
        {
            if($petrolPump->company_id==$loginUserCompanyId)
            return view('petrol-pumps.edit', compact('petrolPump'))->with(['title' => $this->title, 'companies' => $this->companies,'prices'=>$this->prices]);
            else
            abort(403);
        }
        else
        {
            return view('petrol-pumps.edit', compact('petrolPump'))->with(['title' => $this->title, 'companies' => $this->companies,'prices'=>$this->prices]);
        }

        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\UpdatePetrolPumpRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePetrolPumpRequest $request, PetrolPump $petrolPump)
    {
        if ($petrolPump->update($request->all())) {
            return redirect()->route('petrol-pumps.index')->with('success', __('messages.update', ['title' => $this->title]));
        } else {
            return redirect()->back()->with('error', __('messages.try_again'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(PetrolPump $petrolPump)
    {
        if ($petrolPump->delete()) {
            return redirect()->route('petrol-pumps.index')->with('success', __('messages.delete', ['title' => $this->title]));
        } else {
            return redirect()->back()->with('error', __('messages.try_again'));
        }
    }
}

resources/views/petrol-pumps/ajax_data.blade.php
@php 
$tableHeader = ['#','User','Petrol Pump','Code','AVG Rating'];
@endphp

<div class="table-responsive">
    <table class="table table-striped table-hover mt-4">
        <thead>
            <tr class="table-dark ">
                <th>#</th>
                <th>User</th>
                <th>Petrol Pump</th>
                <th>Code</th>
                <th>User AVG Rating</th>
            </tr>
        </thead>
        <tbody>
        <?php if($userRating->count()){  $i=0;foreach($userRating as $avg){?>
            <tr>
                    <td>{{ ++$i }}</td>
                    <td>
                        @if ($avg->user)
                            {{ $avg->user->name }} ( {{ $avg->user->mobile }})
                        @endif
                    </td>
                    <td>
                        @if ($avg->petrolPump)
                            {{ $avg->petrolPump->name }}  
                        @endif
                    </td>
                    <td>
                        @if ($avg->petrolPump)
                            {{ $avg->petrolPump->code }} 
                        @endif
                    </td>
                    
                    <td>{{$avg->avg_rating}}</td>
                </tr>
        <?php }} else {?>    
            <tr>
            <td colspan="5" class="text-white text-center bg-secondary">No record found.</td>
            </tr>
         <?php }?>   
        </tbody>
    </table>
</div>

{{--<x-table :table_header="$tableHeader" :data="$userRating" pagination="true">
            @forelse ($userRating  as $avg )
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>
                        @if ($avg->user)
                            {{ $avg->user->name }} ( {{ $avg->user->mobile }})
                        @endif
                    </td>
                    <td>
                        @if ($avg->petrolPump)
                            {{ $avg->petrolPump->name }}  
                        @endif
                    </td>
                    <td>
                        @if ($avg->petrolPump)
                            {{ $avg->petrolPump->code }} 
                        @endif
                    </td>
                    
                    <td>{{$avg->avg_rating}}
                    <x-link title="{{$avg->avg_rating}}" petrol_pump_id="{{ $avg->petrol_pump_id }}"  user_id="{{$avg->user_id}}" data-toggle="modal" data-target="#model" class="  btn btn-info" icon="" onclick="getUserRating({{ $avg->id }})" id="modal_{{ $avg->id }}" />
                    </td>
                </tr>
            @empty
                <x-norecord colspan="5" />
            @endforelse
</x-table>--}}

resources/views/petrol-pumps/common.blade.php
@push('after-scripts')
    <script>
        $(document).ready(function() {
            $(".form").validate({
                rules: {
                    company_id: "required",
                    price_id: "required",
                    beacon_id: "required",
                    name: "required",
                    code: "required",
                    address: "required",
                    pincode: "required",
                    latitude: "required",
                    longitude: "required",
                    status: "required",
                    opening_time: "required",
                    closing_time:"required",
                     
                }
            });
        });
    </script>
@endpush

resources/views/petrol-pumps/create.blade.php
<!-- Layout  -->
@extends('layouts.admin')
@php
$title = __('messages.create', ['title' => $title]);
$href = route('petrol-pumps.index');
@endphp
@section('title')
    {{ $title }}
@endsection
@section('content')
    <x-card :title="$title">
        @can('petrol-pump-create')
            <x-slot name="header_right">
                <x-link href="{{ $href }}" />
            </x-slot>
        @endcan
        <x-form method="post" action="{{ route('petrol-pumps.store') }}">
            @if(loginUserRoleId()==1)
            <x-select name="company_id" title="Company" :options="$companies" type="select" label_class="required" />
            @else
            <input type="hidden" name="company_id" value="{{loginUserCompanyId()}}">
            @endif
            <x-select name="price_id" title="State" :options="$prices" type="select" label_class="required" />
            
            <x-input name="code" title="Petrol Pump code" label_class="required" />
            <x-input name="beacon_id" title="Petrol Pump Beacon Id" label_class="required" />
            <x-input name="name" title="Petrol Pump name" label_class="required" />
            <x-input type="textarea" name="address" title="Petrol address" />
            <x-input name="pincode" title="Pincode" label_class="required" />
            <x-input name="latitude" title="Latitude" label_class="required" />
            <x-input name="longitude" title="Longitude" label_class="required" />
            <x-input name="opening_time" title="Opening Time (00:00:00)" label_class="required" />
            <x-input name="closing_time" title="Closing Time (00:00:00)" label_class="required" />
            <x-status label_class="required" />
        </x-form>
    </x-card>
@endsection
@include('petrol-pumps.common')

resources/views/petrol-pumps/edit.blade.php
<!-- Layout  -->
@extends('layouts.admin')
@php
$title = __('messages.edit', ['title' => $title]);
$href = route('petrol-pumps.index');

@endphp
@section('title')
    {{ $title }}
@endsection
@section('content')
    <x-card :title="$title">
        <x-slot name="header_right">
            <x-link href="{{ $href }}" />
        </x-slot>
        {!! Form::model($petrolPump, ['method' => 'PUT', 'class' => 'form', 'route' => ['petrol-pumps.update', $petrolPump->id]]) !!}

        @if(loginUserRoleId()==1)
            <x-select name="company_id" title="Company" :options="$companies" type="select" label_class="required" />
            @else
            <input type="hidden" name="company_id" value="{{loginUserCompanyId()}}">
            @endif
        <x-select name="price_id" title="State" :options="$prices" type="select" label_class="required" />
            <x-input name="code" title="Petrol Pump code" label_class="required" />
            <x-input name="beacon_id" title="Petrol Pump Beacon Id" label_class="required" />
            <x-input name="name" title="Petrol Pump name" label_class="required" />
            <x-input type="textarea" name="address" title="Petrol address" />
            <x-input name="pincode" title="Pincode" label_class="required" />
            <x-input name="latitude" title="Latitude" label_class="required" />
            <x-input name="longitude" title="Longitude" label_class="required" />
            <x-input name="opening_time" title="Opening Time (00:00:00)" label_class="required" />
            <x-input name="closing_time" title="Closing Time (00:00:00)" label_class="required" />
            <x-status />
        <div class="mb-3 row">
            <div class="col-sm-8 offset-sm-4">
                <x-button />
            </div>
        </div>
        {!! Form::close() !!}
    </x-card>
@endsection
@include('petrol-pumps.common')

resources/views/petrol-pumps/index.blade.php
<!-- Layout  -->
@extends('layouts.admin')
@php
$title = __('messages.list', ['title' => $title]);
$href = route('petrol-pumps.create');

$tableHeader = ['#','Company','Code','Beacon Id','State','Petrol Price','Name','Address','Pincode', 'Status', 'Created At', 'AVG Rating', 'Action'];
@endphp
@section('title')
    {{ $title }}
@endsection
@section('content')
    <x-card :title="$title">
        @can('petrol-pump-create')
            <x-slot name="header_right">
                <x-link href="{{ $href }}" title="{{ __('messages.create', ['title' =>$title]) }}"
                    icon="fa-plus-circle" />
            </x-slot>
        @endcan
        <x-form with_button="search" method="get" action="{{ route('petrol-pumps.index') }}">
            <div class="row">
                <x-select name="price_id" title="State" :options="$prices" form_type="v"  class="col-md-2" />    
              
                @if(loginUserRoleId()==1)
                <x-select name="company_id" title="Company" :options="$companies" form_type="v"  class="col-md-2" />
                @endif
                 
                <x-input name="code" title="Petrol Pump code" class="col-md-2 col-lg-2 col-xl-2" form_type="v" />
                <x-input name="s" title="Petrol Pump name" class="col-md-2 col-lg-2 col-xl-2" form_type="v" />
                

                <x-status search />

                <x-button type="primary form-control" text="Search" icon="fa-search" button_type="search" />
            </div>

        </x-form>
        <x-table :table_header="$tableHeader" :data="$petrolPumps" pagination="true">
            @forelse ($petrolPumps  as $petrolPump )
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>
                        @if ($petrolPump->company)
                            {{ $petrolPump->company->company_name }}
                        @endif
                    </td>
                    <td>{{ $petrolPump->code }}</td>
                    <td>
                     {{ $petrolPump->beacon_id }}
                    </td>
                    <td>
                        @if ($petrolPump->price)
                            {{ $petrolPump->price->state_name }}
                        @endif
                    </td>
                    <td>
                        @if ($petrolPump->price)
                            {{ $petrolPump->price->petrol_cost }}
                        @endif
                    </td>
                    
                    <td>{{ $petrolPump->name }}</td>
                    <td>{{ $petrolPump->address }}</td>
                    <td>{{ $petrolPump->pincode }}</td>
                    <td>
                        <x-status text="{{ $petrolPump->status }}" />
                    </td>
                    <td>
                        <x-dt :date_time="$petrolPump->created_at" />
                    </td>
                    <td>
                    <x-link title="{{$petrolPump->rating}}" company_name="{{ $petrolPump->company->company_name }}"  petrol_pump_name="{{$petrolPump->name}}" data-toggle="modal" data-target="#model" class="btn btn-info" icon="" onclick="getUserAvgRating({{ $petrolPump->id }})" id="modal_{{ $petrolPump->id }}" />
                    </td>
                    <td>
                   
                        @can('petrol-pump-edit')
                            <x-link title="Edit" icon="fa-edit" href="{{ route('petrol-pumps.edit', $petrolPump->id) }}" />
                        @endcan
                        @can('petrol-pump-delete')
                            <x-delete action="{{ route('petrol-pumps.destroy', $petrolPump->id) }}" />
                        @endcan
                    </td>
                </tr>
            @empty
                <x-norecord colspan="12" />
            @endforelse

        </x-table>
    </x-card>
<x-modal title="Userwise Rating Average" id="model">
    <div class="modal-body">
            <div class="container" id="loaderdata"> </div>
    </div>
</x-modal>
@endsection
@push('after-scripts')
    <script>
        function getUserAvgRating(id, request_from='UserAvgRating')
        {
            $("#loaderdata").html('');
            var petrol_pump_name = $('#modal_'+id).attr('petrol_pump_name');
            var company_name = $('#modal_'+id).attr('company_name');
            $('.modal-title').text(petrol_pump_name+' ('+company_name+')');
            $.ajaxSetup({
                headers: {
                    _token: "{{ csrf_token() }}"
                }
            });
             
            if (id) {
              // addDisabled('.loader');
                $.ajax({
                    url: "{{ route('ajax.request') }}",
                    method: 'GET',
                    data: {
                        petrol_pump_id: id,
                        request_from:request_from
                    },
                    dataType: "html",
                    success: function(result) {  
                        $("#loaderdata").html(result);
                       // removeDisabled('.loader');
                       $('#model').modal('show');
                    }
                });
            } else {
                alert("No Record found");
            }

           
        }
         
    </script>
@endpush