routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/ 
Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['register' => true]);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')
        ->name('home');
    Route::resource('users', 'UserController');
    Route::resource('wallets', 'WalletController');
    Route::resource('vehicles', 'VehicleController');
    Route::resource('mileages', 'MileageController');
    Route::resource('rewards', 'RewardController');
    Route::resource('redeem-gifts', 'RedeemGiftController');
    Route::resource('ratings', 'RatingController');


    Route::resource('companies', 'CompanyController');
    Route::resource('petrol-pumps', 'PetrolPumpController');
    Route::resource('packages', 'PackageController');

    Route::get('change-password', 'UserController@changePassword')->name('change-password');
    Route::post('change-password', 'UserController@updateChangePassword')->name('update-password');
    Route::resource('permissions', 'PermissionController');
   
    Route::resource('roles', 'RoleController');
    Route::resource('prices', 'PriceController');

    Route::resource('transactions', 'TransactionController');
    Route::resource('promotions', 'PromotionController');
    Route::get('ajax/request', 'CompanyController@ajaxRequest')->name('ajax.request');

    Route::resource('logger', 'LoggerController'); 
    Route::resource('services', 'ServiceController'); 
    Route::DELETE('service-detail/{serviceDetail}', 'ServiceController@delete')->name('services.delete');

    Route::post('add-service-detail', 'ServiceController@addServiceDetail')->name('services.add');
     

Route::get('logger-graph', 'LoggerController@graph')->name('logger.graph');

     
});

resources/views/vivek/index.blade.php
<!-- Layout  -->
@extends('layouts.admin')
@php
$title = __('messages.list', ['title' => $title]); 

$tableHeader = ['#', 'Lati','Longi','Accuracy', 'Constellation Details','Consolidated Data','Device','Created At'];
$colorArr = [];
$groupArr = [];
 
@endphp
@section('title')
    {{ $title }}
@endsection
@section('content')
    <x-card :title="$title">
        <x-slot name="header_right">
        <x-link href="{{  route('logger.create')  }}" title="Clear All Data"
                    icon="fa fa-trash" class="btn-danger"/>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <x-link href="{{  route('logger.graph')  }}" title="Graph Data"
                    icon="fa fa-graph" class="btn-warning"/>            
        </x-slot>
        <x-form with_button="search" method="get" action="{{ route('logger.index') }}">
            <div class="row">
                <x-input name="count" title="Common satellite" class="col-md-2 col-lg-2 col-xl-2" form_type="v" input_class="digitonly" />
                <x-input name="s" title="Satellite" class="col-md-4 col-lg-4 col-xl-4" form_type="v" />
                <x-input name="fdate" title="From datetime" class="col-md-3 col-lg-3 col-xl-3" placeholder="YYYY-MM-DD H:i:s" form_type="v" />
                <x-input name="tdate"  placeholder="YYYY-MM-DD HH:ii:ss"  title="To datetime" class="col-md-3 col-lg-3 col-xl-3" form_type="v" />
                <!--div class="col-md-2 form-group col-md-2 col-lg-2 col-xl-2">
                <label for="time" class="">Time</label>
                <select class="form-select" name="time">
                    <option value="1"  >All Data</option>
                    <option value="15">Last 15 Min</option>
                    <option selected="selected"  value="30">Last 30 Min</option>
                    <option value="45">Last 45 Min</option>
                    <option value="60">Last 1 Hour</option>
                    <option value="90">Last 1:30 Hour</option>
                    <option value="120">Last 2 Hour</option>
                </select>
         
                </div-->

                <div class="col-md-4 col-lg-4 col-xl-4">
                    <label for="device_name[]" class="required">Device Name</label>
                    <select class=" form-select  select2"  multiple="" type="select" id="device_name[]" name="device_name[]">
                  <option value="" <?php if(empty($_REQUEST['device_name'])){ echo 'selected="selected"';}?>>All Device</option>
                  <?php if($deviceList){ foreach($deviceList as $v){?>
                  <option value="<?=$v->device_name?>" <?php if(!empty($_REQUEST['device_name'])) { for($c=0;$c<count($_REQUEST['device_name']);$c++){ if($_REQUEST['device_name'][$c]==$v->device_name){ echo 'selected="selected"';}}}?>><?=$v->device_name?></option>
                  <?php }} ?>
                </select>
                
                </div>
                
               
                <x-button type="primary form-control" text="Search" icon="fa-search" button_type="search" />
                
            </div>
        </x-form>
        
        <x-table :table_header="$tableHeader" :data="$loggers" pagination="true">
            @forelse ($loggers  as $data )
                <?php 
                $constellation_count=0;
                $typeExplodeArr =array();
                $typeExplodeUniqueArr =array();
                $nCount = 0;
                if($data->constellation_type)
                {
                $Array = explode(',',$data->constellation_type);
                $nCount = count($Array)-1;
                $typeExplodeArr = array_unique($Array);
                $constellation_count = count($typeExplodeArr)-1;
                $typeExplodeUniqueArr = array_count_values($Array);
                }
                ?> 
                <tr>
                    <td>{{ ++$i }}</td>
                    <td><?=$data->lati?></td>
                    <td><?=$data->longi?></td>
                    <td><?=$data->accuracy?></td>
                    <td>
                    <table>
                    <tr  style="border: 1px solid black;">
                           <th>Constellation Count :</th>
                           <td style="border: 1px solid black;" colspan="<?=$constellation_count?>"><?=$constellation_count?> (<?=$nCount?>)</td>
                    </tr>
                          <tr  style="border: 1px solid black;">
                           <th>Constellation Group Type :</th>
                           <?php if($typeExplodeArr){$inc=1; foreach($typeExplodeArr as $key=>$value){
                             
                             
                             
                              if($inc<count($typeExplodeArr)){?>
                           <td  style="border: 1px solid black;">
                              <?php  echo $value;  ?>
                           </td>  
                          <?php }$inc++;}} ?>
                          </tr>
                          <tr  style="border: 1px solid black;">
                           <th>Constellation Val Count :</th>
                          
                           <?php if($typeExplodeArr){ $inc=1;foreach($typeExplodeArr as $key=>$value){ if($inc<count($typeExplodeArr)){?>
                            
                            <td  style="border: 1px solid black;">
                              <?php echo $typeExplodeUniqueArr[$value];?>
                            </td>

                             <?php } $inc++;}} ?>
                         
                          </tr>
                    </table>       
                    </td>

                    <td>
                    <?php 
                     $tyArray = explode(',',$data->constellation_type);
                     $vArray = explode(',',$data->vehicle_id);
                    
                     for($a=0;$a<count($vArray)-1;$a++){
                       
                      
                      if (!array_key_exists($tyArray[$a],$colorArr))
                      {
                        $colorArr[$tyArray[$a]]['vehicle'][]=$vArray[$a]; 
                        $colorArr[$tyArray[$a]]['color'][]=sprintf('#%06X', mt_rand(0, 0xFFFFFF)); 
                      }
                      else
                      {
                        if(!empty($colorArr) and !in_array($vArray[$a],$colorArr[$tyArray[$a]]['vehicle']))
                       {
                        $colorArr[$tyArray[$a]]['vehicle'][]=$vArray[$a]; 
                        $colorArr[$tyArray[$a]]['color'][]=sprintf('#%06X', mt_rand(0, 0xFFFFFF)); 
                       }
                      }
                      
                      }
                     //echo "<pre>";print_r($colorArr);
                    ?>   
                         <table>
                           <tr  style="border: 1px solid black;">
                           <th>Vehicle:</th>
                             <?php $vArray = explode(',',$data->vehicle_id);
                             for($a=0;$a<count($vArray)-1;$a++){
                               
                              if(in_array($vArray[$a], $colorArr[$tyArray[$a]]['vehicle']))
                              {  $key = array_search($vArray[$a], $colorArr[$tyArray[$a]]['vehicle']);   $color = $colorArr[$tyArray[$a]]['color'][$key];
                              }
                              else { $color = '';  }
                               ?>
                                
                             <td bgcolor="<?=$color;?>" style="border: 1px solid black;"><?=$vArray[$a]?></td>

                             <?php }?>
                           </tr> 
                           <tr  style="border: 1px solid black;">
                           <th>Azimuth:</th>
                             <?php $aArray = explode(',',$data->azimuth);
                             for($a=0;$a<count($aArray)-1;$a++){
                               
                              if(in_array($vArray[$a], $colorArr[$tyArray[$a]]['vehicle']))
                              {  $key = array_search($vArray[$a], $colorArr[$tyArray[$a]]['vehicle']);   $color = $colorArr[$tyArray[$a]]['color'][$key];
                              }
                              else { $color = '';  }
                               
                               ?>
                             <td  bgcolor="<?=$color;?>"  style="border: 1px solid black;"><?=$aArray[$a]?></td>
                             <?php }?>
                           </tr> 
                           <tr  style="border: 1px solid black;">
                            <th>Elevation:</th>
                            <?php $eArray = explode(',',$data->elevation);
                                  for($a=0;$a<count($eArray)-1;$a++){  if(in_array($vArray[$a], $colorArr[$tyArray[$a]]['vehicle']))
                                    {  $key = array_search($vArray[$a], $colorArr[$tyArray[$a]]['vehicle']);   $color = $colorArr[$tyArray[$a]]['color'][$key];
                                    }
                                    else { $color = '';  }?>
                                  <td  bgcolor="<?=$color;?>"  style="border: 1px solid black;"><?=$eArray[$a]?></td>
                                  <?php }?>
                            </tr> 
                            <tr>
                       <th  style="border: 1px solid black;">CNHZ:</th>          
                            <?php $cnhzArray = explode(',',$data->cnhz);
                             for($a=0;$a<count($cnhzArray)-1;$a++){ 
                              if(in_array($vArray[$a], $colorArr[$tyArray[$a]]['vehicle']))
                              {  $key = array_search($vArray[$a], $colorArr[$tyArray[$a]]['vehicle']);   $color = $colorArr[$tyArray[$a]]['color'][$key];
                              }
                              else { $color = '';  }?>
                             <td  bgcolor="<?=$color;?>"  style="border: 1px solid black;"><?=$cnhzArray[$a]?></td>
                             <?php }?>
                           </tr> 
                           <tr  style="border: 1px solid black;">
                       <th>Constellation type:</th>
                       <?php //$tyArray = explode(',',$data->constellation_type);
                             for($a=0;$a<count($tyArray)-1;$a++){  if(in_array($vArray[$a], $colorArr[$tyArray[$a]]['vehicle']))
                              {  $key = array_search($vArray[$a], $colorArr[$tyArray[$a]]['vehicle']);   $color = $colorArr[$tyArray[$a]]['color'][$key];
                              }
                              else { $color = '';  }?>
                             <td  bgcolor="<?=$color;?>" style="border: 1px solid black;"><?=$tyArray[$a]?></td>
                             <?php }?>
                           </tr>
                          </table>
                          
                    </td>
                    <td><?=!empty($data->device_name)?str_replace(',',' | ',$data->device_name):'NA'?></td>
                   
                    
                    <td><?=$data->created_at?></td>
                </tr>
            @empty
                <x-norecord colspan="11" />
            @endforelse

        </x-table>

         
    </x-card>
@endsection

resources/views/vivek/view.blade.php
<!-- Layout  -->
@extends('layouts.admin')
@php
$title = __('messages.list', ['title' => $title]); 
/*$deviceList = array(
  'redmi'=>'redmi',
  'samsung'=>'samsung'
);*/
 
@endphp
@section('title')
    {{ $title }}
@endsection
@section('content')
    <x-card :title="$title">
    
        <x-slot name="header_right">
         <x-link href="{{  route('logger.index')  }}" title="Back"
                    icon="fa fa-graph" class="btn-primary"/>            
        </x-slot>
         
        <x-form with_button="search" method="get" action="{{ route('logger.graph') }}">
            <div class="row">
                <x-input name="s" title="Vehicle Id" class="col-md-2 col-lg-2 col-xl-2" form_type="v" input_class="digitonly" />
                <x-input name="group" title="Group" class="col-md-2 col-lg-2 col-xl-2" form_type="v" />
                <x-input name="fdate" title="From datetime" class="col-md-2 col-lg-2 col-xl-2" placeholder="YYYY-MM-DD H:i:s" form_type="v" />
                <x-input name="tdate"  placeholder="YYYY-MM-DD HH:ii:ss"  title="To datetime" class="col-md-2 col-lg-2 col-xl-2" form_type="v" />
                
                <div class="col-md-2 col-lg-2 col-xl-2">
                    <label for="device_name[]" class="required">Device Name</label>
                    <select class=" form-select  select2"  multiple="" type="select" id="device_name[]" name="device_name[]">
                  <option value="" <?php if(empty($_REQUEST['device_name'])){ echo 'selected="selected"';}?>>All Device</option>
                  <?php if($deviceList){ foreach($deviceList as $v){?>
                  <option value="<?=$v->device_name?>" <?php if(!empty($_REQUEST['device_name'])) { for($c=0;$c<count($_REQUEST['device_name']);$c++){ if($_REQUEST['device_name'][$c]==$v->device_name){ echo 'selected="selected"';}}}?>><?=$v->device_name?></option>
                  <?php }} ?>
                </select>
                
                </div>
                
                
                <!--x-select name="device_name[]" input_class="select2"  label_class="required" multiple
                title="Device Name" :options="$deviceList" type="select" form_type="v"/-->
                

                <x-button type="primary form-control" text="Search" icon="fa-search" button_type="search" />
            </div>
        </x-form>
        
        <?php 
        $groupNo =  app('request')->input('group');
        $vehicleNo = app('request')->input('s');
        $graphArray = array();
        $childArr = array();
foreach ($loggers  as $data ) 
{
  /*echo "Vehicle : ".$data->vehicle_id;
  echo "<br/>";
  echo "constellation_type: ".$data->constellation_type;
  echo "<br/>";
  echo "azimuth: ".$data->azimuth;
  echo "<br/>";
  echo "<br/>";*/
  
  $constellationTypeArray=explode(',',$data->constellation_type);
  $vehicleArray=explode(',',$data->vehicle_id);
  $azimuthArray=explode(',',$data->azimuth);
  $elevationArray=explode(',',$data->elevation);
  $constellationFilterArray =array();
  //echo $groupNo;exit;
  $constellationFilterArray = array_filter($constellationTypeArray, function($number) use ($groupNo) {  
    if($number==$groupNo)
    {
      return $number;
    }
    
  });
  if($constellationFilterArray)
  {
    foreach($constellationFilterArray as $key=>$val)
    {
      
      if($vehicleArray[$key]==$vehicleNo)
      {
       $graphArray['created_at'][]=$data->created_at; 
       $graphArray['device_name'][]=$data->device_name; 
       $graphArray['vehicleNo'][]=$vehicleNo;
       $graphArray['groupNo'][]=$groupNo;
       $graphArray['constellation_type'][]=$constellationTypeArray[$key];
       $graphArray['vehicle_id'][]=$vehicleArray[$key];
       $graphArray['azimuth'][]=$azimuthArray[$key];
       $graphArray['elevation'][]=$elevationArray[$key];
        

       
      }
     
    }
   
    
    //echo "<pre/>";print_r($graphArray);
     }
 
  //$typeExplodeArr = array_unique($array);
  // echo "<pre/>";print_r($mapArray);
  
}
 //echo "<pre/>";print_r($graphArray);
?>     

  
<div class="row mt-4 row-cols-2">
            <div class="col" style="width:100%">
              <div class="card mb-4">
                <div class="card-header">Azimuth Chart</div>
                <div class="card-body">
                  <div class="c-chart-wrapper">
                    <canvas id="canvas-1"></canvas>
                  </div>
                </div>
              </div>
            </div>
</div>

<div class="row mt-4 row-cols-2">
            <div class="col" style="width:100%">
              <div class="card mb-4">
                <div class="card-header">Elevation</div>
                <div class="card-body">
                  <div class="c-chart-wrapper">
                    <canvas id="canvas-2"></canvas>
                  </div>
                </div>
              </div>
            </div>
</div>

    </x-card>
@endsection
@push('after-scripts')
<script src="{{ asset('js/chart.js/js/chart.min.js') }}"></script>
<script src="{{ asset('js/@coreui/chartjs/js/coreui-chartjs.js') }}"></script>
<!--script src="{{ asset('js/chart/charts.js') }}"></script-->
<script>
  let colorArr=[];
  <?php if($deviceList){ foreach($deviceList as $v){?>
    colorArr.push(getRandomColor());
  <?php  }}?>
     console.log(colorArr);
  const barChart = new Chart(document.getElementById('canvas-1'), {
  type: 'line',
  data: {
    labels: [<?php if($graphArray){ foreach ($graphArray['created_at']  as $key=>$data ) {?>'<?=$data?>', <?php }}?> ],
    datasets: [
      <?php if($deviceList){ $i=0;foreach($deviceList as $v){?>
      {
      label: '<?=$v->device_name?>',          
      backgroundColor: colorArr[<?=$i?>],
      borderColor:colorArr[<?=$i?>],
      pointBackgroundColor: colorArr[<?=$i?>],
      pointBorderColor: '#f00',
      data: [<?php if($graphArray){ foreach ($graphArray['azimuth']  as $key=>$data ) { if($v->device_name==$graphArray['device_name'][$key]) { echo $data; }   ?>, <?php }}?>]
        },
        <?php $i++;}} ?>   
]
  },
  options: {
    responsive: true
  }
}); 

 
const barChart_1 = new Chart(document.getElementById('canvas-2'), {
  type: 'line',
  data: {
    labels: [<?php if($graphArray){ foreach ($graphArray['created_at']  as $key=>$data ) {?>'<?=$data?>', <?php }}?> ],
    datasets: [
      <?php if($deviceList){ $i=0;foreach($deviceList as $v){?>
      {
      label: '<?=$v->device_name?>',          
      backgroundColor: colorArr[<?=$i?>],
      borderColor:colorArr[<?=$i?>],
      pointBackgroundColor: colorArr[<?=$i?>],
      pointBorderColor: '#f00',
      data: [<?php if($graphArray){ foreach ($graphArray['elevation']  as $key=>$data ) { if($v->device_name==$graphArray['device_name'][$key]) { echo $data; }   ?>, <?php }}?>]
        },
        <?php $i++;}} ?>   
]
  },
  options: {
    responsive: true
  }
}); 
  
function getRandomColor() {
            var letters = '0123456789ABCDEF'.split('');
            var color = '#';
            for (var i = 0; i < 6; i++ ) {
                color += letters[Math.floor(Math.random() * 16)];
            }
            return color;
                }
  </script>

@endpush